name: Check for updates

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: tools/scraper/package-lock.json

      - name: Set up environment
        run: |
          mkdir -p out/packages

          [ -r out/.version ] && VERSION=$(cat out/.version)
          [ -r out/.md5 ] && ARTIFACTS_HASH=$(cat out/.md5)

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "ARTIFACTS_HASH=${ARTIFACTS_HASH}" >> $GITHUB_ENV

          echo "Current WhatsApp Web version: ${VERSION:-none}"
          echo "Current artifacts md5: ${ARTIFACTS_HASH:-none}"

      - name: Install scraper dependencies
        run: |
          cd tools/scraper
          npm install

      - name: Scrap proto files
        run: |
          node tools/scraper

          NEWEST_VERSION=$(cat out/.version)
          NEWEST_ARTIFACTS_HASH=$(find out -type f ! -name '.*' -exec md5sum {} + | sort | md5sum | tr -d ' \n-')
          NEWEST_BUILD_HASH=$(echo -n "$NEWEST_VERSION" | md5sum | cut -d' ' -f1)

          echo $NEWEST_ARTIFACTS_HASH > out/.md5

          echo "NEWEST_VERSION=$NEWEST_VERSION" >> $GITHUB_ENV
          echo "NEWEST_BUILD_HASH=$NEWEST_BUILD_HASH" >> $GITHUB_ENV
          echo "NEWEST_ARTIFACTS_HASH=$NEWEST_ARTIFACTS_HASH" >> $GITHUB_ENV

          echo "Newest WhatsApp Web version: $NEWEST_VERSION"
          echo "Newest proto md5: $NEWEST_ARTIFACTS_HASH"

      - name: Check if package update is needed
        run: |
          if [[ "${{ env.ARTIFACTS_HASH }}" == "${{ env.NEWEST_ARTIFACTS_HASH }}" ]]; then
            echo "No update needed - artifacts hash is the same."
          elif [[ "${{ env.VERSION }}" == "${{ env.NEWEST_VERSION }}" ]]; then
            echo "Cannot update - version is the same but artifacts differ. Need new WhatsApp Web version."
          else
            echo "Update needed - both version and artifacts are different."
            echo "package_update_needed=true" >> $GITHUB_ENV
          fi

      - name: Install packager dependencies
        if: env.package_update_needed == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Generate packages
        if: env.package_update_needed == 'true'
        run: bash generate.sh
        working-directory: tools/packager
        env:
          OUT_DIR: ${{ github.workspace }}/out

      - name: Upload artifacts
        if: env.package_update_needed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: |
            out
            !node_modules

      - name: Publish packages
        if: env.package_update_needed == 'true' && github.ref == 'refs/heads/main'
        run: bash publish.sh
        working-directory: tools/packager
        env:
          DIST_DIR: ${{ github.workspace }}/out/.dist
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        if: env.package_update_needed == 'true' && github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "WhatsApp Web v${{ env.NEWEST_VERSION }}"
          tagging_message: "v${{ env.NEWEST_VERSION }}"
